API PYTHON
PedroChaparro/PI202202-alako-backend pull request #12
Opened 2022-08-31 15:58 UTC by PedroChaparro

API para la transformación del texto del usuario a un vector (Paso anterior al procesamiento con SCALA). 

- Se utiliza el framework **bottle** de python ya que solo depende de la librería estándar de Python. 
- La imagen de docker tiene un peso cercano a los 4GB debido a las múltiples dependencias del paquete **sentence_transformers**.

Las instrucciones para probar en local o en Docker se encuentran en el archivo README.md.

2022-09-08 14:11 UTC, Woynert requested changes
Una vez corre, funciona muy bien

2022-09-10 15:55 UTC, PedroChaparro commented on docker/vectorize_api/Dockerfile
> +FROM python:latest
De acuerdo, ¿Estaría bien dejar la versión más actual fija?

2022-09-10 15:58 UTC, Woynert commented on docker/vectorize_api/Dockerfile
> +FROM python:latest
Idealmente, si.

2022-09-10 16:44 UTC, PedroChaparro commented on docker/vectorize_api/Dockerfile
> +CMD ["python", "./src/api.py"]
Arreglado

2022-09-10 22:28 UTC, Woynert approved these changes
Excelente

2022-09-11 22:44 UTC, andres123dbh approved these changes

2022-09-13 14:06 UTC, SilviaPabon reviewed
Genial!

2022-09-13 14:06 UTC, SilviaPabon approved these changes

2022-09-13 14:06 UTC, merged