Algoritmo de búsqueda coseno de similitud
PedroChaparro/PI202202-alako-backend pull request #16
Opened 2022-09-28 20:56 UTC by PedroChaparro

Para iniciar leer `/scala/src/main/scala/cosine/README.md`

Características: 

1. Obtiene los argumentos desde consola. 
2. Utiliza el **hdfs** para acceder a los datos de manera distribuída, por lo que no fue necesario utilizar el método `.paralelize()` de spark. 
3. Calcula el coseno de similitud de la búsqueda del usuario **frente a todos los datos recolectados en el json**
4. Si el coseno de similitud es mayor o igual al 50% se agrega a un Json Array que es enviado a de regreso a la API de Scala. 

To do: 
- [ ] POST a la API de Scala para enviar el JSON con el resultado final. 
- [ ] Recibir el **uuid** como argumento (Actualmente solo se recibe el vector del vídeo del usuario)

2022-10-01 13:12 UTC, Woynert requested changes
Todo lo relacionado a lo que era el `_ScalaBaseProject` se puede borrar. Entonces en lugar de `/scala/src/main/scala/cosine` sencillamente usar `/cosine`.

2022-10-01 13:14 UTC, PedroChaparro commented
> Todo lo relacionado a lo que era el `_ScalaBaseProject` se puede borrar. Entonces en lugar de `/scala/src/main/scala/cosine` sencillamente usar `/cosine`.

Justo quería pregutnarle eso, voy

2022-10-01 18:17 UTC, SilviaPabon approved these changes
Genial 🥳

2022-10-01 22:12 UTC, andres123dbh approved these changes

2022-10-03 18:13 UTC, Woynert approved these changes
Estupendo

2022-10-03 18:13 UTC, merged