Dedicated docker compose files for production machines
PedroChaparro/PI202202-alako-backend pull request #18
Opened 2022-10-01 12:38 UTC by Woynert

2022-10-01 19:00 UTC, PedroChaparro requested changes
Hay que cambiar el `COPY . . ` del archivo `/docker/vectorize_api/Dockerfile` a `COPY ./vectorize_api .`, de lo contrario copia todo el directorio `/docker` dentro del contenedor de Python.

2022-10-04 02:21 UTC, PedroChaparro approved these changes
Buenísimo!

2022-10-04 02:29 UTC, SilviaPabon approved these changes
👍🏻

2022-10-04 02:56 UTC, andres123dbh approved these changes

2022-10-04 02:56 UTC, merged