Create README.md
PedroChaparro/PI202202-alako-backend pull request #36
Opened 2022-10-28 01:04 UTC by PedroChaparro

Create readme file.

2022-10-28 13:47 UTC, Woynert requested changes

2022-10-28 13:47 UTC, Woynert commented on README.md
> +- Search algorithm (See [this](https://github.com/PedroChaparro/PI202202-alako-backend/tree/development/docker/cosine) folder for more details:
Este link va a la rama development. Si se cambia el link a la rama Main el directorio no existe actualmente, pero se puede asumir que existirá una vez se haga merge.

2022-10-28 13:47 UTC, Woynert commented on README.md
> +- Docker images and docker-compose files (See [this](https://github.com/PedroChaparro/PI202202-alako-backend/tree/development/docker) folder for more details):
Este link va a la rama development

2022-10-28 15:42 UTC, Woynert approved these changes

2022-10-28 19:42 UTC, SilviaPabon approved these changes

2022-10-29 15:07 UTC, andres123dbh approved these changes

2022-10-29 15:07 UTC, merged